# Generated by Django 5.1.5 on 2025-01-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customusermodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard User'), ('gold', 'Gold User')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.usergroupmodel'),
        ),
    ]
