# Generated by Django 5.1.5 on 2025-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usergroupmodel_customusermodel_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroupmodel',
            options={'verbose_name': 'User-Group', 'verbose_name_plural': 'User-Groups'},
        ),
        migrations.AlterModelTable(
            name='usergroupmodel',
            table='custom_user_groups',
        ),
    ]
