# Generated by Django 5.1.5 on 2025-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usergroupmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupmodel',
            name='name',
            field=models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold')], max_length=20, unique=True),
        ),
    ]
