# Generated by Django 5.1.5 on 2025-01-27 17:54

import account.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usergroupmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='group',
            field=models.ForeignKey(blank=True, default=account.models.user.get_default_group, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.usergroupmodel'),
        ),
    ]
