# Generated by Django 5.1.5 on 2025-01-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customusermodel_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroupmodel',
            options={'permissions': [('can_transfer_money', 'Can transfer money')], 'verbose_name': 'User-Group', 'verbose_name_plural': 'User-Groups'},
        ),
    ]
