# Generated by Django 5.1.5 on 2025-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_usergroupmodel_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroupmodel',
            options={'verbose_name': 'User-Group', 'verbose_name_plural': 'User-Groups'},
        ),
        migrations.AddField(
            model_name='usergroupmodel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group'),
        ),
    ]
