# Generated by Django 5.1.5 on 2025-01-27 19:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_projectsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
