# Generated by Django 5.1 on 2025-01-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_alter_transactionmodel_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionmodel",
            old_name="transaction_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="transactionmodel",
            old_name="type",
            new_name="transaction_type",
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="current_stage",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transactionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
