# Generated by Django 5.1 on 2025-01-31 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0007_rename_transaction_date_transactionmodel_created_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionmodel",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
