# Generated by Django 5.1 on 2025-02-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_alter_transactionmodel_receiver"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTypesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("started_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment Type",
                "verbose_name_plural": "Payment Types",
                "db_table": "payment_types",
            },
        ),
        migrations.RemoveField(
            model_name="projectsmodel",
            name="slug",
        ),
        migrations.AlterField(
            model_name="projectsmodel",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="operations.paymenttypesmodel",
            ),
        ),
    ]
