# Generated by Django 5.1 on 2025-02-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_alter_paymenttransactionmodel_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactionmodel",
            name="prefix",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
