# Generated by Django 5.1 on 2025-02-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0012_paymenttransactionmodel_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransactionmodel",
            name="prefix",
        ),
    ]
