# Generated by Django 5.1 on 2025-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0014_paymenttransactionmodel_current_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactionmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
