# Generated by Django 5.1 on 2025-02-04 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0015_paymenttransactionmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransactionmodel",
            name="transaction_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="transaction_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
