# Generated by Django 5.1 on 2025-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0018_transfertransactionmodel_delete_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransactionmodel",
            name="value",
        ),
        migrations.RemoveField(
            model_name="paymenttransactionmodel",
            name="value_type",
        ),
        migrations.AddField(
            model_name="paymenttransactionmodel",
            name="payment_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="paymenttransactionmodel",
            name="total_stages",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="paymenttypesmodel",
            name="required_inputs",
            field=models.JSONField(default=dict),
        ),
    ]
