# Generated by Django 5.1 on 2025-02-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0019_remove_paymenttransactionmodel_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransactionmodel",
            name="transaction_type",
            field=models.CharField(default="payment", max_length=50),
        ),
    ]
